import { Food } from "@/types/food";

export const foodCompleteList: Food[] = [
  // em tratamento
  { name: "Não ingerir: Açúcar (cristal, refinado, demerada, mascavo, adoçante, Stévia, Sucralose)", type: "treatment" },
  { name: "Não ingerir: Água com gás", type: "treatment" },
  { name: "Não ingerir: Álcool (vinhos, cervejas, licores, whiskies)", type: "treatment" },
  { name: "Não ingerir: Amendoim (castanha ou pasta)", type: "treatment" },
  { name: "Não ingerir: Aveia", type: "treatment" },
  { name: "Não ingerir: Café (coado, espresso, solúvel, descafeinado, nenhum tipo)", type: "treatment" },
  { name: "Não ingerir: Carne vermelha", type: "treatment" },
  { name: "Não ingerir: Chás (preto, hortelã, orégano)", type: "treatment" },
  { name: "Não ingerir: Cevada (chá)", type: "treatment" },
  { name: "Não ingerir: Conservas (milho, ervilha, pepino, beterraba, palmito, etc)", type: "treatment" },
  { name: "Não ingerir: Farinhas (trigo, aveia, grão de bico, quinoa, nenhum tipo)", type: "treatment" },
  { name: "Não ingerir: Frutas desidratadas ou cristalizadas (tâmara, banana, uva, ameixa, tamara)", type: "treatment" },
  { name: "Não ingerir: Glúten (pães, farináceos)", type: "treatment" },
  { name: "Não ingerir: Industrializados (molhos, enlatados, embutidos, processados, chips, salgadinho, refrigerantes, bolachas, biscoitos, barra de cereal, macarrão)", type: "treatment" },
  { name: "Não ingerir: Leite (integral, zero, desnatado, vegetal, aveia, soja, nenhum tipo)", type: "treatment" },
  { name: "Não ingerir: Mel ou melado", type: "treatment" },
  { name: "Não ingerir: Óleo vegetal (soja, girassol, canola, coco)", type: "treatment" },
  { name: "Não ingerir: Refrigerantes", type: "treatment" },

  { name: "Abobrinhas", type: "acid"},
  { name: "Açúcar (cristal, refinado, demerada, mascavo, adoçante, Stévia, Sucralose)", type: "acid" },
  { name: "Água com gás (rever)", type: "acid" },
  { name: "Arroz (integral, negro)", type: "acid" },
  { name: "Álcool (vinhos, cervejas, licores, whiskies)", type: "acid" },
  { name: "Amendoim (castanha ou pasta) (rever)", type: "alkaline" },
  { name: "Aveia (rever)", type: "alkaline" },
  { name: "Azeite de oliva extra virgem", type: "acid" },
  { name: "Azeitona in natura", type: "acid" },
  { name: "Bacalhau", type: "acid" },
  { name: "Cacau amargo (chocolate)", type: "acid" },
  { name: "Café (coado, espresso, solúvel, descafeinado, nenhum tipo)", type: "acid" },
  { name: "Carne de frango", type: "acid" },
  { name: "Carne vermelha", type: "acid" },
  { name: "Chá verde", type: "acid" },
  { name: "Chás (preto, hortelã, orégano)", type: "acid" },
  { name: "Cevada (chá)", type: "acid" },
  { name: "Coco (natural, ralado)", type: "acid" },
  { name: "Conservas (milho, ervilha, pepino, beterraba, palmito, etc)", type: "acid" },
  { name: "Ervilha (seca, partida)", type: "acid" },
  { name: "Farinhas (trigo, aveia, grão de bico, quinoa, nenhum tipo)", type: "acid" },
  { name: "Feijão (preto, marrom, carioca, vermelho)", type: "acid" },
  { name: "Frutas desidratadas ou cristalizadas (tâmara, banana, uva)", type: "acid" },
  { name: "Fubá", type: "acid" },
  { name: "Glúten (pães, farináceos)", type: "acid" },
  { name: "Gorduras em geral", type: "acid" },
  { name: "Industrializados (molhos, enlatados, embutidos, processados, chips, salgadinho, refrigerantes, bolachas, biscoitos, barra de cereal, macarrão)", type: "acid" },
  { name: "Leite (integral, zero, desnatado, vegetal, aveia, soja, nenhum tipo)", type: "acid" },
  { name: "Lentilha", type: "acid" },
  { name: "Mandioca", type: "acid" },
  { name: "Mel ou melado (rever)", type: "acid" },
  { name: "Milho", type: "acid" },
  { name: "Molho de tomate feito em casa", type: "acid" },
  { name: "Nozes", type: "acid" },
  { name: "Óleo vegetal (soja, girassol, canola, coco)", type: "acid" },
  { name: "Ovos", type: "acid" },
  { name: "Peixes não de cativeiros (tilápia)", type: "acid" },
  { name: "Refrigerantes", type: "acid" },
  { name: "Salmão selvagem", type: "acid" },
  { name: "Semente de girassol", type: "acid" },

  
  { name: "Abóbora (paulista, cabotiá)", type: "alkaline" },
  { name: "Abacate", type: "alkaline" },
  { name: "Abacaxi", type: "alkaline" },
  { name: "Agrião", type: "alkaline" },
  { name: "Alface", type: "alkaline" },
  { name: "Alho", type: "alkaline" },
  { name: "Almeirão", type: "alkaline" },
  { name: "Amaranto", type: "alkaline" },
  { name: "Ameixa (fruta natural)", type: "alkaline" },
  { name: "Amêndoas", type: "alkaline" },
  { name: "Amoras", type: "alkaline" },
  { name: "Aspargos", type: "alkaline" },
  { name: "Apricot, damasco (fruta natural)", type: "alkaline" },
  { name: "Ata (pinha)", type: "alkaline" },
  { name: "Avelã (castanha natural)", type: "alkaline" },
  { name: "Bananas (maçã, caturra, da terra)", type: "alkaline" },
  { name: "Batatas (doce, inglesa, yacon, salsa)", type: "alkaline" },
  { name: "Beterraba (natural)", type: "alkaline" },
  { name: "Berinjela", type: "alkaline" },
  { name: "Brócolis", type: "alkaline" },
  { name: "Cajá caju", type: "alkaline" },
  { name: "Castanhas em geral", type: "alkaline" },
  { name: "Cebolas (roxa, branca)", type: "alkaline" },
  { name: "Cebolinha", type: "alkaline" },
  { name: "Cenoura", type: "alkaline" },
  { name: "Cereja", type: "alkaline" },
  { name: "Chia", type: "alkaline" },
  { name: "Chuchu", type: "alkaline" },
  { name: "Coentro", type: "alkaline" },
  { name: "Cogumelos", type: "alkaline" },
  { name: "Couves (couve flor)", type: "alkaline" },
  { name: "Ervilhas in natura congeladas", type: "alkaline" },
  { name: "Espinafre", type: "alkaline" },
  { name: "Farinha de amaranto ou quinoa", type: "alkaline" },
  { name: "Feijão verde", type: "alkaline" },
  { name: "Framboesa", type: "alkaline" },
  { name: "Gergelim", type: "alkaline" },
  { name: "Graviola", type: "alkaline" },
  { name: "Jiló", type: "alkaline" },
  { name: "Linhaça", type: "alkaline" },
  { name: "Maçãs", type: "alkaline" },
  { name: "Mamão", type: "alkaline" },
  { name: "Mangas", type: "alkaline" },
  { name: "Maxixe", type: "alkaline" },
  { name: "Morango", type: "alkaline" },
  { name: "Melancia", type: "alkaline" },
  { name: "Melão", type: "alkaline" },
  { name: "Pepinos", type: "alkaline" },
  { name: "Pera", type: "alkaline" },
  { name: "Pêssego", type: "alkaline" },
  { name: "Pimentão", type: "alkaline" },
  { name: "Quiabo", type: "alkaline" },
  { name: "Quinoa", type: "alkaline" },
  { name: "Rabanete", type: "alkaline" },
  { name: "Repolho", type: "alkaline" },
  { name: "Salsinha", type: "alkaline" },
  { name: "Sapoti", type: "alkaline" },
  { name: "Semente de abóbora", type: "alkaline" },
  { name: "Tomates", type: "alkaline" },
  { name: "Uvas", type: "alkaline" },
  { name: "Vagem", type: "alkaline" },
]
